import streamlit as st
import pandas as pd
import io
import re

# ==========================================
# 1. KONFIGURASI HALAMAN & DATABASE
# ==========================================

# Menambahkan page_icon (ikon tab browser)
st.set_page_config(
    page_title="Sarkes Generator", 
    layout="wide", 
    page_icon="🏥"
)

# CSS Custom untuk Tombol & Tampilan
st.markdown("""
    <style>
    div.stButton > button:first-child {
        background-color: #009b54;
        color: white;
        border: none;
    }
    div.stButton > button:hover {
        background-color: #4ed60e;
        color: white;
        border: none;
    }
    </style>
""", unsafe_allow_html=True)

csv_data = """KATEGORI,JENIS PEMERIKSAAN,KODE,BATAS NILAI/PARAMETER,KESIMPULAN,SARAN KHUSUS,KESIMPULAN (English),SARAN KHUSUS (English)
FISIK,Nadi,Taki,>100,Takikardia (nadi [XXX] kali/menit),Lakukan pemeriksaan EKG dan konsultasi dengan dokter spesialis jantung jika ada keluhan berdebar-debar atau nyeri dada,Tachycardia (pulse [XXX] bpm),"Perform an ECG evaluation and consult a cardiologist if palpitations or chest pain occur"
FISIK,Nadi,Bradi,<60,Bradikardia (nadi [XX] kali/menit),"Lakukan pemeriksaan EKG dan konsultasi dengan dokter spesialis jantung jika ada keluhan berdebar-debar, pingsan atau nyeri dada",Bradycardia (pulse [XX] bpm),"Perform an ECG evaluation and consult a cardiologist if palpitations, fainting, or chest pain occur"
FISIK,Tekanan Darah,PreHT,120-139/80-89,Prehipertensi ([XXX/XX] mmHg),Monitor tekanan darah secara berkala,Prehypertension ([XXX/XX] mmHg),Monitor blood pressure regularly
FISIK,Tekanan Darah,HT1,140-159/90-100,Hipertensi stage 1 ([XXX/XX] mmHg),Minum obat antihipertensi dan monitor tekanan darah secara berkala,Stage 1 Hypertension ([XXX/XX] mmHg),Take antihypertensive medication and monitor blood pressure regularly
FISIK,Tekanan Darah,HT2,>=160/>=100,Hipertensi stage 2 ([XXX/XXX] mmHg),Minum obat antihipertensi dan monitor tekanan darah secara berkala,Stage 2 Hypertension ([XXX/XXX] mmHg),Take antihypertensive medication and monitor blood pressure regularly
FISIK,Tekanan Darah,RHT TK,>=140/>=90,Riwayat hipertensi tidak terkontrol (tekanan darah saat ini [XXX/XX] mmHg),Minum obat antihipertensi dan monitor tekanan darah secara berkala,Uncontrolled hypertension (current blood pressure [XXX/XX] mmHg),Take antihypertensive medication and monitor blood pressure regularly
FISIK,Tekanan Darah,RHT Kontrol,<=140/<=90,Riwayat hipertensi terkontrol (tekanan darah saat ini [XXX/XX] mmHg),Minum obat antihipertensi dan monitor tekanan darah secara berkala,Controlled hypertension (current blood pressure [XXX/XX] mmHg),Take antihypertensive medication and monitor blood pressure regularly
FISIK,Indeks Massa Tubuh,Sentral,">=25.0, LP >=80","Obesitas sentral (IMT [XX.X] kg/m2, lingkar perut [YY] cm)",Turunkan BB hingga BB ideal,"Central obesity (BMI [XX.X] kg/m2, waist circumference [YY] cm)",Reduce body weight to achieve an ideal body weight
FISIK,Indeks Massa Tubuh,OB1,25.0-29.9,Obesitas grade 1 (IMT [XX.X] kg/m2),Turunkan BB hingga BB ideal,Grade 1 Obesity (BMI [XX.X] kg/m2),Reduce body weight to achieve an ideal body weight
FISIK,Indeks Massa Tubuh,OB2,>=30.0,Obesitas grade 2 (IMT [XX.X] kg/m2),Turunkan BB hingga BB ideal,Grade 2 Obesity (BMI [XX.X] kg/m2),Reduce body weight to achieve an ideal body weight
FISIK,Indeks Massa Tubuh,Obes,>=25.0,Obesitas (IMT [XX.X] kg/m2),Turunkan BB hingga BB ideal,Obesity (BMI [XX.X] kg/m2),Reduce body weight to achieve an ideal body weight
FISIK,Indeks Massa Tubuh,Over,23.0-24.9,Overweight (IMT [XX.X] kg/m2),Turunkan BB hingga BB ideal,Overweight (BMI [XX.X] kg/m2),Reduce body weight to achieve an ideal body weight
FISIK,Indeks Massa Tubuh,Under,<18.5,Underweight (IMT [XX.X] kg/m2),"Tingkatkan asupan protein dan olahraga secara teratur (3-5x/minggu, minimal 30 menit) untuk meningkatkan massa otot",Underweight (BMI [XX.X] kg/m2),"Increase body weight to achieve an ideal body weight - Increase protein intake and exercise regularly (3-5x/week, at least 30 minutes) to increase muscle mass"
FISIK,Visus,[OD; OS; ODS] Miop,TKM,"[OD; OS; ODS] Miopia, tanpa kacamata",Konsultasi dengan dokter spesialis mata untuk koreksi visus mata dengan kacamata yang sesuai,"Myopia in [OD; OS; ODS], without glasses",Consult an ophthalmologist for visual acuity correction with appropriate glasses
FISIK,Visus,[OD; OS; ODS] Miop,DKM,"[OD; OS; ODS] Miopia, belum terkoreksi optimal dengan kacamata",Konsultasi dengan dokter spesialis mata untuk koreksi visus mata dengan kacamata yang sesuai,"Myopia in [OD; OS; ODS], not optimally corrected with glasses",Consult an ophthalmologist for visual acuity correction with appropriate glasses
FISIK,Visus,[OD; OS; ODS] Miop,Koreksi,"[OD; OS; ODS] Miopia, terkoreksi optimal dengan kacamata",Konsultasi dengan dokter spesialis mata jika ada keluhan penurunan penglihatan dengan kacamata yang sudah ada,"Myopia in [OD; OS; ODS], optimally corrected with glasses",Consult an ophthalmologist if there is any visual problem with current glasses
FISIK,Visus,[OD; OS; ODS] Hiper,TKM,"[OD; OS; ODS] Hipermetropia, tanpa kacamata",Konsultasi dengan dokter spesialis mata untuk koreksi visus mata dengan kacamata yang sesuai,"Hypermetropia in [OD; OS; ODS], without glasses",Consult an ophthalmologist for visual acuity correction with appropriate glasses
FISIK,Visus,[OD; OS; ODS] Hiper,DKM,"[OD; OS; ODS] Hipermetropia, belum terkoreksi optimal dengan kacamata",Konsultasi dengan dokter spesialis mata untuk koreksi visus mata dengan kacamata yang sesuai,"Hypermetropia in [OD; OS; ODS], not optimally corrected with glasses",Consult an ophthalmologist for visual acuity correction with appropriate glasses
FISIK,Visus,[OD; OS; ODS] Hiper,Koreksi,"[OD; OS; ODS] Hipermetropia, terkoreksi optimal dengan kacamata",Konsultasi dengan dokter spesialis mata jika ada keluhan penurunan penglihatan dengan kacamata yang sudah ada,"Hypermetropia in [OD; OS; ODS], optimally corrected with glasses",Consult an ophthalmologist if there is any visual problem with current glasses
FISIK,Visus,[OD; OS; ODS] Pres,TKM,"[OD; OS; ODS] Presbiopia, tanpa kacamata",Konsultasi dengan dokter spesialis mata untuk koreksi visus mata dengan kacamata yang sesuai,"Presbyopia in [OD; OS; ODS], without glasses",Consult an ophthalmologist for visual acuity correction with appropriate glasses
FISIK,Visus,[OD; OS; ODS] Pres,DKM,"[OD; OS; ODS] Presbiopia, belum terkoreksi optimal dengan kacamata",Konsultasi dengan dokter spesialis mata untuk koreksi visus mata dengan kacamata yang sesuai,"Presbyopia in [OD; OS; ODS], not optimally corrected with glasses",Consult an ophthalmologist for visual acuity correction with appropriate glasses
FISIK,Visus,[OD; OS; ODS] Pres,Koreksi,"[OD; OS; ODS] Presbiopia, terkoreksi optimal dengan kacamata",Konsultasi dengan dokter spesialis mata jika ada keluhan penurunan penglihatan dengan kacamata yang sudah ada,"Presbyopia in [OD; OS; ODS], optimally corrected with glasses",Consult an ophthalmologist if there is any visual problem with current glasses
FISIK,Pterigium,[OD; OS; ODS] PTR,Grade 1-3,Pterigium grade [G] di [OD; OS; ODS] ,"Gunakan pelindung mata/kacamata hitam saat beraktivitas di luar ruangan untuk menghindari paparan debu, angin dan sinar matahari",Grade [G] Pterygium in [OD; OS; ODS],"Use eye protection/sunglasses during outdoor activities to avoid exposure to dust, wind, and sunlight"
FISIK,Buta Warna,BW,Parsial,Buta warna parsial,Dapat ditempatkan pada pekerjaan yang tidak membutuhkan ketelitian warna,Partial color blindness,Can be placed in jobs that do not require color discrimination
FISIK,Telinga,Serumen [AD; AS; ADS],,Serumen di [AD; AS; ADS],Konsultasi dengan dokter spesialis THT untuk pembersihan/evakuasi serumen di [AD; AS; ADS],Cerumen in [AD; AS; ADS],Consult an ENT specialist for cerumen evacuation in [AD; AS; ADS]
FISIK,Telinga,Prop [AD; AS; ADS],,Serumen prop di [AD; AS; ADS],Konsultasi dengan dokter spesialis THT untuk pembersihan/evakuasi serumen di [AD; AS; ADS],Cerumen prop in [AD; AS; ADS],Consult an ENT specialist for cerumen evacuation in [AD; AS; ADS]
FISIK,Telinga,HL [AD; AS; ADS],,Kesan penurunan pendengaran di [AD; AS; ADS],Lakukan pemeriksaan audiometri dan konsultasi dengan dokter spesialis THT untuk pemeriksaan dan tata laksana lebih lanjut terkait kesan penurunan pendengaran di [AD; AS; ADS],Impression of hearing loss in [AD; AS; ADS],Perform audiometry and consult an ENT specialist for further evaluation and management regarding hearing loss in [AD; AS; ADS]
FISIK,Tonsil,Tonsil,Ukuran T2/T2; T3/T3; T4/T4,Hipertrofi tonsil [TT/TT],Konsultasi dengan dokter spesialis THT untuk pemeriksaan dan tata laksana lebih lanjut terkait pembesaran/hipertrofi tonsil,Tonsillar hypertrophy [TT/TT],Consult an ENT specialist for further evaluation and management of tonsillar hypertrophy
FISIK,Faring,Faring,Hiperemis,Faring hiperemis,Konsultasi dengan dokter spesialis THT untuk pemeriksaan dan tata laksana lebih lanjut terkait temuan faringitis,Pharyngeal hyperemia,Consult an ENT specialist for further evaluation and management of pharyngitis findings
FISIK,Mammae,MM [D; S; DS],,Benjolan di payudara [D; S; DS],Konsultasi dengan dokter spesialis bedah onkologi untuk pemeriksaan dan tata laksana lebih lanjut terkait temuan benjolan di payudara [D; S; DS],Lump in [D; S; DS] breast,Consult a surgical oncologist for further evaluation and management of breast lump findings in [D; S; DS] breast
FISIK,Thoraks,Jantung,Bising,Terdapat bising jantung,Konsultasi dengan dokter spesialis jantung untuk pemeriksaan dan tata laksana lebih lanjut terkait temuan jantung abnormal,Heart murmur,Consult a cardiologist for further evaluation and management of abnormal heart findings
FISIK,Thoraks,Paru,Wheezing,Terdapat wheezing pada paru,Konsultasi dengan dokter spesialis paru untuk pemeriksaan dan tata laksana lebih lanjut terkait temuan paru abnormal,Wheezing in lungs,Consult a pulmonologist for further evaluation and management of abnormal lung findings
FISIK,Abdomen,NT,Epi,Nyeri tekan epigastrium,Konsultasi dengan dokter spesialis penyakit dalam untuk pemeriksaan dan tata laksana lebih lanjut terkait nyeri tekan epigastrium,Epigastric tenderness,Consult an internist for further evaluation and management of epigastric tenderness
FISIK,Abdomen,Ketok [D; S; DS],,Nyeri ketok ginjal [D; S; DS],Konsultasi dengan dokter spesialis penyakit dalam untuk pemeriksaan dan tata laksana lebih lanjut terkait nyeri ketok ginjal [D; S; DS],[D; S; DS] Costovertebral angle tenderness,Consult an internist for further evaluation and management of [D; S; DS] Costovertebral angle tenderness
FISIK,Genital perianal,HI,Grade 1-4,Hemorrhoid interna grade [G],"Tingkatkan asupan serat (sayur dan buah), minum air putih minimal 2L/hari dan hindari aktivitas duduk terlalu lama - Konsultasi dengan dokter spesialis bedah untuk pemeriksaan dan tata laksana lebih lanjut terkait temuan hemorroid interna",Grade [G] Internal hemorrhoid,"Increase fiber intake (vegetables and fruits), drink at least 2L of water/day, and avoid prolonged sitting - Consult a surgeon for further evaluation and management of internal hemorrhoid findings"
FISIK,Genital perianal,HE,Eksterna,Hemorrhoid eksterna,"Tingkatkan asupan serat (sayur dan buah), minum air putih minimal 2L/hari dan hindari aktivitas duduk terlalu lama - Konsultasi dengan dokter spesialis bedah untuk pemeriksaan dan tata laksana lebih lanjut terkait temuan hemorroid eksterna",External hemorrhoid,"Increase fiber intake (vegetables and fruits), drink at least 2L of water/day and avoid prolonged sitting - Consult a surgeon for further evaluation and management of external hemorrhoids"
FISIK,Ekstremitas,EXT Kaki O,,Bentuk kaki O,Konsultasi dengan dokter spesialis orthopedi untuk pemeriksaan dan tata laksana lebih lanjut terkait temuan bentuk kaki O,O-shaped legs,Consult an orthopedic specialist for further evaluation and management of O-shaped legs
FISIK,Ekstremitas,EXT Kaki X,,Bentuk kaki X,Konsultasi dengan dokter spesialis orthopedi untuk pemeriksaan dan tata laksana lebih lanjut terkait temuan bentuk kaki X,X-shaped legs,Consult an orthopedic specialist for further evaluation and management of X-shaped legs
FISIK,Gigi,Gigi,Jumlah 1-32,"Gigi: Gigi Hilang ([X]), Sisa Akar ([R]), Abrasi ([A]), Karies ([C]), Karang Gigi ([E]), Perawatan Saluran Akar ([M]), Tumpatan ([F]), Impaksi ([I]), Gigi Palsu ([P]), Gigi Patah ([FR])",Konsultasi dengan dokter gigi untuk perawatan gigi,"Teeth: Missing teeth ([X]), Root remnant ([R]), Abrasion ([A]), Caries ([C]), Calculus ([E]), Root canal treatment ([M]), Filling ([F]), Impaction ([I]), Denture ([P]), Fractured tooth ([FR])",Consult a dentist for dental treatment
LAB,Hematologi,HB,>=15.0,Peningkatan Hemoglobin [XX.X] g/dL,,Increased Hemoglobin [XX.X] g/dL,
LAB,Hematologi,Poli,HB >16.0,Suspek polisithemia (Hemoglobin [XX.X] g/dL),Konsultasi dengan dokter spesialis penyakit dalam untuk pemeriksaan dan tata laksana lebih lanjut terkait suspek polisitemia,Suspect polycythemia (Hemoglobin [XX.X] g/dL),Consult an internist for further evaluation and management of suspected polycythemia
LAB,Hematologi,ANN,HB  <12.0,Anemia normositik normokromik (Hemoglobin [XX.X] g/dL),"Tingkatkan asupan makanan yang mengandung zat besi (sayuran hijau, daging merah, hati), hindari teh dan kopi - Konsultasi dengan dokter spesialis penyakit dalam untuk pemeriksaan dan tata laksana lebih lanjut terkait anemia",Normocytic normochromic anemia (Hemoglobin [XX.X] g/dL),"Increase intake of iron-rich foods (green vegetables, red meat, liver), avoid tea and coffee - Consult an internist for further evaluation and management of anemia"
LAB,Hematologi,ANM,"HB <12.0, MCV <=80.0,  MCH <=26.0","Anemia mikrositik hipokromik (Hemoglobin [XX.X] g/dL, MCV [YY.Y] fL, MCH [ZZ.Z] pg)","Tingkatkan asupan makanan yang mengandung zat besi (sayuran hijau, daging merah, hati), hindari teh dan kopi - Konsultasi dengan dokter spesialis penyakit dalam untuk pemeriksaan dan tata laksana lebih lanjut terkait anemia","Microcytic hypochromic anemia (Hemoglobin [XX.X] g/dL, MCV [YY.Y] fL, MCH [ZZ.Z] pg)","Increase intake of iron-rich foods (green vegetables, red meat, liver), avoid tea and coffee - Consult an internist for further evaluation and management of anemia"
LAB,Hematologi,Eritro,>5.0,Eritrositosis [X.X] x 10^6/uL,Konsultasi dengan dokter spesialis penyakit dalam untuk pemeriksaan dan tata laksana lebih lanjut terkait eritrositosis,Erythrocytosis [X.X] x 10^6/uL,Consult an internist for further evaluation and management of erythrocytosis
LAB,Hematologi,LKS,>=12.0,Leukositosis [XX.X] x 10^3/uL --> suspek infeksi bakteri,Konsultasi dengan dokter spesialis penyakit dalam untuk pemeriksaan dan tata laksana lebih lanjut terkait leukositosis,Leukocytosis [XX.X] x 10^3/uL --> suspected bacterial infection,Consult an internist for further evaluation and management of leukocytosis
LAB,Hematologi,LKT,10.0-11.9,Peningkatan leukosit [XX.X] x 10^3/uL,Konsultasi dengan dokter spesialis penyakit dalam untuk pemeriksaan dan tata laksana lebih lanjut terkait peningkatan leukosit,Increased leukocytes [XX.X] x 10^3/uL,Consult an internist for further evaluation and management of increased leukocytes
LAB,Hematologi,LKP,<4.0,Leukopenia [X.X] x 10^3/uL,Konsultasi dengan dokter spesialis penyakit dalam untuk pemeriksaan dan tata laksana lebih lanjut terkait leukositosis,Leukopenia [X.X] x 10^3/uL,Consult an internist for further evaluation and management of leukopenia
LAB,Hematologi,Eos,4.0-6.9,Peningkatan eosinofil [X.X] %,Hindari faktor pencetus alergi,Increased eosinophils [X.X] %,Avoid allergy triggers
LAB,Hematologi,Eos,>=7.0,Eosinofilia [X.X] %,"Hindari faktor pencetus alergi - Konsultasi dengan dokter spesialis penyakit dalam untuk pemeriksaan dan tata laksana lebih lanjut terkait eosinofilia",Eosinophilia [X.X] %,"Avoid allergy triggers - Consult an internist for further evaluation and management of eosinophilia"
LAB,Hematologi,LED,>15,Peningkatan LED [XX] mm/jam,Jaga stamina tubuh Anda,Increased ESR [XX] mm/hour,Maintain your body stamina
LAB,Hematologi,Fraksi HB,,Ditemukan fraksi hemoglobin varian,Lakukan pemeriksaan analisa hemoglobin,A hemoglobin variant fraction was found,Perform hemoglobin analysis
LAB,Hematologi,PLT,<=150,Trombositopenia [XXX] x 10^3/uL,Konsultasi dengan dokter spesialis penyakit dalam untuk pemeriksaan dan tata laksana lebih lanjut terkait trombositopenia,Thrombocytopenia [XXX] x 10^3/uL,Consult an internist for further evaluation and management of thrombocytopenia
LAB,Hematologi,PLT,>=450,Trombositosis [XXX] x 10^3/uL,Konsultasi dengan dokter spesialis penyakit dalam untuk pemeriksaan dan tata laksana lebih lanjut terkait trombositosis,Thrombocytosis [XXX] x 10^3/uL,Consult an internist for further evaluation and management of thrombocytosis
LAB,Glukosa,GDP,100-125,"Hiperglikemia, glukosa puasa [XXX] mg/dL --> suspek prediabetes","Turunkan kadar glukosa darah dan lakukan pemeriksaan HbA1c secara berkala setiap 3 bulan - Diet rendah gula dan karbohidrat","Hyperglycemia, fasting glucose [XXX] mg/dL --> suspected prediabetes","Lower blood glucose levels and perform HbA1c test regularly every 3 months - Low sugar and carbohydrate diet"
LAB,Glukosa,GDP,>=126,"Hiperglikemia, glukosa puasa [XXX] mg/dL --> suspek Diabetes Mellitus","Turunkan kadar glukosa darah dan lakukan pemeriksaan HbA1c secara berkala setiap 3 bulan - Diet rendah gula dan karbohidrat","Hyperglycemia, fasting glucose [XXX] mg/dL --> suspected Diabetes Mellitus","Reduce blood glucose levels and perform HbA1c checks regularly every 3 months - Low sugar and carbohydrate diet"
LAB,Glukosa,GDP,>=130 (RDM),Riwayat Diabetes Mellitus tidak terkontrol (Glukosa puasa saat ini [XXX] mg/dL),"Minum obat antidiabetes secara rutin, monitor kadar glukosa darah dan lakukan pemeriksaan HbA1c secara berkala setiap 3 bulan - Diet rendah gula dan karbohidrat",Uncontrolled Diabetes Mellitus (Current fasting glucose [XXX] mg/dL),"Take antidiabetic medication regularly, monitor blood glucose levels, and perform HbA1c test regularly every 3 months - Low sugar and carbohydrate diet"
LAB,Glukosa,GDP,<130 (RDM),Riwayat Diabetes Mellitus terkontrol (Glukosa puasa saat ini [XXX] mg/dL),"Minum obat antidiabetes secara rutin, monitor kadar glukosa darah dan lakukan pemeriksaan HbA1c secara berkala setiap 3 bulan - Diet rendah gula dan karbohidrat",Controlled Diabetes Mellitus (Current fasting glucose [XXX] mg/dL),"Take antidiabetic medication regularly, monitor blood glucose levels, and perform HbA1c test regularly every 3 months - Low sugar and carbohydrate diet"
LAB,Glukosa,HbA1c,5.7-6.4,Peningkatan HbA1c [X.X] % --> suspek prediabetes,"Turunkan kadar glukosa darah dan lakukan pemeriksaan HbA1c secara berkala setiap 3 bulan - Diet rendah gula dan karbohidrat",Increased HbA1c [X.X] % --> suspected prediabetes,"Lower blood glucose levels and perform HbA1c test regularly every 3 months - Low sugar and carbohydrate diet"
LAB,Glukosa,HbA1c,>=6.5,Peningkatan HbA1c [X.X] % --> suspek Diabetes Mellitus,"Turunkan kadar glukosa darah dan lakukan pemeriksaan HbA1c secara berkala setiap 3 bulan - Diet rendah gula dan karbohidrat",Increased HbA1c [X.X] % --> suspected Diabetes Mellitus,"Reduce blood glucose levels and perform HbA1c checks regularly every 3 months - Low sugar and carbohydrate diet"
LAB,Glukosa,HbA1c,>=7.0 (RDM),Riwayat Diabetes Mellitus tidak terkontrol (HbA1c saat ini [X.X] %),"Minum obat antidiabetes secara rutin, monitor kadar glukosa darah dan lakukan pemeriksaan HbA1c secara berkala setiap 3 bulan - Diet rendah gula dan karbohidrat",Uncontrolled Diabetes Mellitus (Current HbA1c [X.X] %),"Take antidiabetic medication regularly, monitor blood glucose levels, and perform HbA1c test regularly every 3 months - Low sugar and carbohydrate diet"
LAB,Glukosa,HbA1c,<7.0 (RDM),Riwayat Diabetes Mellitus terkontrol (HbA1c saat ini [X.X] %),"Minum obat antidiabetes secara rutin, monitor kadar glukosa darah dan lakukan pemeriksaan HbA1c secara berkala setiap 3 bulan - Diet rendah gula dan karbohidrat",Controlled Diabetes Mellitus (Current HbA1c [X.X] %),"Take antidiabetic medication regularly, monitor blood glucose levels, and perform HbA1c test regularly every 3 months - Low sugar and carbohydrate diet"
LAB,Lipid Profile,TC,200-239,Kolesterol total dalam batas tinggi [XXX] mg/dL,Diet rendah lemak,Borderline high total cholesterol [XXX] mg/dL,Low fat diet
LAB,Lipid Profile,TC,>=240,Kolesterol total tinggi [XXX] mg/dL,Diet rendah lemak,High total cholesterol [XXX] mg/dL,Low fat diet
LAB,Lipid Profile,LDL,100-129,Kolesterol LDL Direk mendekati optimal [XXX] mg/dL,Diet rendah lemak,Near-optimal direct LDL cholesterol [XXX] mg/dL,Low fat diet
LAB,Lipid Profile,LDL,130-159,Kolesterol LDL Direk dalam batas tinggi [XXX] mg/dL,Diet rendah lemak,Borderline high direct LDL cholesterol [XXX] mg/dL,Low fat diet
LAB,Lipid Profile,LDL,160-189,Kolesterol LDL Direk tinggi [XXX] mg/dL,Diet rendah lemak,High direct LDL cholesterol [XXX] mg/dL,Low fat diet
LAB,Lipid Profile,LDL,>=190,Kolesterol LDL Direk sangat tinggi [XXX] mg/dL,Diet rendah lemak,Very high direct LDL cholesterol [XXX] mg/dL,Low fat diet
LAB,Lipid Profile,HDL,<40,Kolesterol HDL rendah [XX] mg/dL,Diet rendah lemak,Low HDL cholesterol [XX] mg/dL,Low fat diet
LAB,Lipid Profile,TG,150-199,Trigliserida dalam batas tinggi [XXX] mg/dL,Diet rendah lemak dan karbohidrat,Borderline high triglycerides [XXX] mg/dL,Low fat and carbohydrate diet
LAB,Lipid Profile,TG,200-499,Trigliserida tinggi [XXX] mg/dL,Diet rendah lemak dan karbohidrat,High triglycerides [XXX] mg/dL,Low fat and carbohydrate diet
LAB,Lipid Profile,TG,>=500,Trigliserida sangat tinggi [XXX] mg/dL,Diet rendah lemak dan karbohidrat,Very high triglycerides [XXX] mg/dL,Low fat and carbohydrate diet
LAB,Faal Ginjal,AU,>=5.7,Hiperurisemia [X.X] mg/dL,Diet rendah purin,Hyperuricemia [X.X] mg/dL,Low purine diet
LAB,Faal Ginjal,Kreat,>0.90,Peningkatan kreatinin [X.XX] mg/dL,Konsultasi dengan dokter spesialis penyakit dalam untuk pemeriksaan dan tata laksana lebih lanjut terkait peningkatan kreatinin,Elevated creatinine [X.XX] mg/dL,Consult an internist for further evaluation and management of increased creatinine
LAB,Faal Ginjal,GGJ,>0.90 (eLFG >=60),"Suspek gangguan fungsi ginjal (Kreatinin [X.XX] mg/dL, eLFG [YY] mL/menit/1.73 m2)",Konsultasi dengan dokter spesialis penyakit dalam untuk pemeriksaan dan tata laksana lebih lanjut terkait suspek gangguan fungsi ginjal,"Suspected renal function impairment (Creatinine [X.XX] mg/dL, eGFR [YY] mL/min/1.73 m2)",Consult an internist for further evaluation and management of suspected renal function impairment
LAB,Faal Ginjal,FGJ,>0.90 (eLFG <60),"Suspek penurunan fungsi ginjal (Kreatinin [X.XX] mg/dL, eLFG [YY] mL/menit/1.73 m2)",Konsultasi dengan dokter spesialis penyakit dalam untuk pemeriksaan dan tata laksana lebih lanjut terkait suspek penurunan fungsi ginjal,"Suspected decreased renal function (Creatinine [X.XX] mg/dL, eGFR [YY] mL/min/1.73 m2)",Consult an internist for further evaluation and management of suspected decreased renal function
LAB,Faal hati,Hati GOT,>=27,Peningkatan enzim hati (GOT [XX] U/L),Konsultasi dengan dokter spesialis penyakit dalam untuk pemeriksaan dan tata laksana lebih lanjut terkait peningkatan enzim hati,Elevated liver enzymes (GOT [XX] U/L),Consult an internist for further evaluation and management of increased liver enzymes
LAB,Faal hati,Hati GPT,>=34,Peningkatan enzim hati (GPT [XX] U/L),Konsultasi dengan dokter spesialis penyakit dalam untuk pemeriksaan dan tata laksana lebih lanjut terkait peningkatan enzim hati,Elevated liver enzymes (GPT [XX] U/L),Consult an internist for further evaluation and management of increased liver enzymes
LAB,Faal hati,Hati ALL,GOT >=27 & GPT >=34,"Peningkatan enzim hati (GOT [XX] U/L, GPT [YY] U/L)",Konsultasi dengan dokter spesialis penyakit dalam untuk pemeriksaan dan tata laksana lebih lanjut terkait peningkatan enzim hati,"Elevated liver enzymes (GOT [XX] U/L, GPT [YY] U/L)",Consult an internist for further evaluation and management of increased liver enzymes
LAB,Faal hati,GGH GOT,>=54,Suspek gangguan fungsi hati (GOT [XX] U/L),Konsultasi dengan dokter spesialis penyakit dalam untuk pemeriksaan dan tata laksana lebih lanjut terkait suspek gangguan fungsi hati,Suspected liver function impairment (GOT [XX] U/L),Consult an internist for further evaluation and management of suspected liver function impairment
LAB,Faal hati,GGH GPT,>=68,Suspek gangguan fungsi hati (GPT [XX] U/L),Konsultasi dengan dokter spesialis penyakit dalam untuk pemeriksaan dan tata laksana lebih lanjut terkait suspek gangguan fungsi hati,Suspected liver function impairment (GPT [XX] U/L),Consult an internist for further evaluation and management of suspected liver function impairment
LAB,Faal hati,GGH ALL,GOT >=54 & GPT>=68,"Suspek gangguan fungsi hati (GOT [XX] U/L, GPT [YY] U/L)",Konsultasi dengan dokter spesialis penyakit dalam untuk pemeriksaan dan tata laksana lebih lanjut terkait suspek gangguan fungsi hati,"Suspected liver function impairment (GOT [XX] U/L, GPT [YY] U/L)",Consult an internist for further evaluation and management of suspected liver function impairment
LAB,Faal hati,HBsAg,Reaktif,HBsAg Reaktif,"Konsultasi dengan dokter spesialis penyakit dalam untuk pemeriksaan dan tata laksana lebih lanjut terkait temuan HBsAg reaktif - Lakukan pemeriksaan imunologi/serologi untuk menentukan status infeksi Hepatitis B",HBsAg Reactive,"Consult an internist for further evaluation and management of reactive HBsAg findings - Perform immunology/serology tests to determine Hepatitis B infection status"
LAB,Faal hati,AntiHBs,NR,Belum pernah terpapar dan belum memiliki kekebalan/antibodi terhadap virus Hepatitis B,Vaksinasi Hepatitis B untuk memberikan kekebalan terhadap virus Hepatitis B,Has not been exposed and does not have immunity/antibodies to Hepatitis B virus,Hepatitis B vaccination to provide immunity against Hepatitis B virus
LAB,Faal hati,AntiHBs,Reaktif,Sudah terbentuk antibodi/kekebalan terhadap virus Hepatitis B,,Has immunity/antibody against Hepatitis B virus formed,
LAB,Mikronutrien,Vit D,<20.0,Defisiensi vitamin D (Vitamin D 25-OH Total [XX.X] ng/mL),"Tingkatkan paparan sinar matahari pagi selama ±5–15 menit setiap hari, terutama pada area tangan dan kaki. Perbanyak konsumsi makanan kaya vitamin D (ikan laut, telur, susu, keju), serta pertimbangkan suplementasi vitamin D sesuai anjuran dokter",Vitamin D deficiency (Vitamin D 25-OH Total [XX.X] ng/mL),"Increase morning sun exposure for ±5–15 minutes daily, especially on arms and legs. Increase consumption of Vitamin D rich foods (sea fish, eggs, milk, cheese), and consider Vitamin D supplementation as advised by a doctor"
LAB,Mikronutrien,Vit D,>=20.0-29.9,Insufisiensi vitamin D (Vitamin D 25-OH Total [XX.X] ng/mL),"Tingkatkan paparan sinar matahari pagi selama ±5–15 menit setiap hari, terutama pada area tangan dan kaki. Perbanyak konsumsi makanan kaya vitamin D (ikan laut, telur, susu, keju), serta pertimbangkan suplementasi vitamin D sesuai anjuran dokter",Vitamin D insufficiency (Vitamin D 25-OH Total [XX.X] ng/mL),"Increase morning sun exposure for ±5–15 minutes daily, especially on arms and legs. Increase consumption of Vitamin D rich foods (sea fish, eggs, milk, cheese), and consider Vitamin D supplementation as advised by a doctor"
LAB,Urinalisa,Alb,[text_input],Albuminuria [text_input] mg/dL,Konsultasi dengan dokter spesialis urologi untuk pemeriksaan dan tata laksana lebih lanjut terkait hasil urinalisa abnormal,Albuminuria [text_input] mg/dL,Consult a urologist for further evaluation and management of abnormal urinalysis results
LAB,Urinalisa,keton,[text_input],Ketonuria [text_input] mg/dL,Konsultasi dengan dokter spesialis urologi untuk pemeriksaan dan tata laksana lebih lanjut terkait hasil urinalisa abnormal,Ketonuria [text_input] mg/dL,Consult a urologist for further evaluation and management of abnormal urinalysis results
LAB,Urinalisa,LE,[text_input],"Leukosituria [text_input]/uL, sedimen leukosit [text_input]/LPB",Konsultasi dengan dokter spesialis urologi untuk pemeriksaan dan tata laksana lebih lanjut terkait hasil urinalisa abnormal,"Leukocyturia [text_input]/uL, leukocyte sediment [text_input]/HPF",Consult a urologist for further evaluation and management of abnormal urinalysis results
LAB,Urinalisa,Glukosuria,[text_input],Glukosuria [text_input] mg/dL,Konsultasi dengan dokter spesialis urologi untuk pemeriksaan dan tata laksana lebih lanjut terkait hasil urinalisa abnormal,Glucosuria [text_input] mg/dL,Consult a urologist for further evaluation and management of abnormal urinalysis results
LAB,Urinalisa,hema,[text_input],"Hematuria [text_input]/uL, sedimen eritrosit [text_input]/LPB",Konsultasi dengan dokter spesialis urologi untuk pemeriksaan dan tata laksana lebih lanjut terkait hasil urinalisa abnormal,"Hematuria [text_input]/uL, erythrocyte sediment [text_input]/HPF",Consult a urologist for further evaluation and management of abnormal urinalysis results
LAB,Urinalisa,Kristal,,Kristaluria normal amorf urat (+)/LPB,Minum air putih minimal 2L/hari,Crystalluria normal amorphous urate (+)/HPF,Drink at least 2L of water/day
LAB,Urinalisa,urob,[text_input],Urobilinogenuria [text_input] mg/dL,Konsultasi dengan dokter spesialis urologi untuk pemeriksaan dan tata laksana lebih lanjut terkait hasil urinalisa abnormal,Urobilinogenuria [text_input] mg/dL,Consult a urologist for further evaluation and management of abnormal urinalysis results
LAB,Urinalisa,Silinder kasar,[text_input],Silinder berbutir kasar [text_input]/LPK,Minum air putih minimal 2L/hari,Coarse granular cast [text_input]/LPF,Drink at least 2L of water/day
LAB,Urinalisa,Silinder halus,[text_input],Silinder berbutir halus [text_input]/LPK,Minum air putih minimal 2L/hari,Fine granular cast [text_input]/LPF,Drink at least 2L of water/day
LAB,Urinalisa,Epitel,[text_input],Epitel skuamosa [text_input]/LPK,Minum air putih minimal 2L/hari,Squamous epithelium [text_input]/LPF,Drink at least 2L of water/day
LAB,Urinalisa,Bakteri,,Bakteriuria (+)/LPB,Hindari kebiasaan menahan BAK dan jaga higienitas area genitalia,Bacteriuria (+)/HPF,Avoid delaying urination and maintain proper genital hygiene
LAB,Feses,FS,Parasit,Ditemukan parasit blastocystis hominis (+) pada feses,Konsultasi dengan dokter spesialis penyakit dalam untuk pemeriksaan dan tata laksana lebih lanjut terkait hasil analisa feses abnormal,Parasite blastocystis hominis (+) found in feces,Consult an internist for further evaluation and management of abnormal fecal analysis results
LAB,Feses,FS,Leuko,Ditemukan leukosit 0-1/LPB pada feses,Konsultasi dengan dokter spesialis penyakit dalam untuk pemeriksaan dan tata laksana lebih lanjut terkait hasil analisa feses abnormal,Leukocytes 0-1/HPF found in feces,Consult an internist for further evaluation and management of abnormal fecal analysis results
LAB,Feses,FS,Eri,Ditemukan eritrosit 0-1/LPB pada feses,Konsultasi dengan dokter spesialis penyakit dalam untuk pemeriksaan dan tata laksana lebih lanjut terkait hasil analisa feses abnormal,Erythrocytes 0-1/HPF found in feces,Consult an internist for further evaluation and management of abnormal fecal analysis results
RONTGEN ,Thorax,Ro,Bronchitis,Rontgen Thorax: Bronchitis,Konsultasi dengan dokter spesialis paru untuk pemeriksaan dan tata laksana lebih lanjut terkait temuan rontgen thorax abnormal,Chest X-ray: Bronchitis,Consult a pulmonologist for further evaluation and management of abnormal chest X-ray findings
RONTGEN ,Thorax,Ro,Cardiomegali,Rontgen Thorax: Cardiomegali,Konsultasi dengan dokter spesialis jantung untuk pemeriksaan dan tata laksana lebih lanjut terkait temuan rontgen thorax abnormal,Chest X-ray: Cardiomegaly,Consult a cardiologist for further evaluation and management of abnormal chest X-ray findings
RONTGEN ,Thorax,Ro,Scoliosis,Rontgen Thorax: Dextroscoliosis thoracalis,Konsultasi dengan dokter spesialis orthopedi untuk pemeriksaan dan tata laksana lebih lanjut terkait temuan rontgen thorax abnormal,Chest X-ray: Dextroscoliosis thoracalis,Consult an orthopedic specialist for further evaluation and management of abnormal chest X-ray findings
AUDIOMETRI,Audiometri,Audio [AD; AS; ADS],[text_input],Audiometri [AD; AS; ADS]: [text_input],"Evaluasi faktor risiko dan etiologi terkait hasil audiometri [AD; AS; ADS] abnormal - Konsul dokter spesialis THT untuk pemeriksaan dan tatalaksana lebih lanjut terkait hasil audiometri [AD; AS; ADS] abnormal",[AD; AS; ADS] audiometry: [text_input],"Evaluate risk factors and etiology regarding abnormal audiometry results on [AD; AS; ADS] - Consult an ENT specialist for further evaluation and management of abnormal audiometry results on [AD; AS; ADS]"
SPIROMETRI,Spirometri,Spiro,Restriksi ringan,Spirometri: Restriksi ringan,Tingkatkan olahraga aerobik,Spirometry: Mild restriction,Increase aerobic exercise
SPIROMETRI,Spirometri,Spiro,Restriksi sedang,Spirometri: Restriksi sedang,"Tingkatkan olahraga aerobik - Konsul dokter spesialis paru untuk pemeriksaan dan tatalaksana lebih lanjut terkait hasil spirometri abnormal",Spirometry: Moderate restriction,"Increase aerobic exercise - Consult a pulmonologist for further evaluation and management of abnormal spirometry results"
SPIROMETRI,Spirometri,Spiro,Obstruksi ringan,Spirometri: Obstruksi ringan,Tingkatkan olahraga aerobik,Spirometry: Mild obstruction,Increase aerobic exercise
SPIROMETRI,Spirometri,Spiro,Obstruksi sedang,Spirometri: Obstruksi sedang,"Tingkatkan olahraga aerobik - Konsul dokter spesialis paru untuk pemeriksaan dan tatalaksana lebih lanjut terkait hasil spirometri abnormal",Spirometry: Moderate obstruction,"Increase aerobic exercise - Consult a pulmonologist for further evaluation and management of abnormal spirometry results"
EKG,EKG,EKG Taki,100-150,EKG: Sinus tachycardia HR [XXX] bpm normoaxis,Konsultasi dengan dokter spesialis jantung jika ada keluhan terkait hasil EKG abnormal,ECG: Sinus tachycardia HR [XXX] bpm normoaxis,Consult a cardiologist if there are complaints regarding abnormal ECG results
EKG,EKG,EKG Bradi,30-59,EKG: Sinus bradycardia HR [XX] bpm normoaxis,Konsultasi dengan dokter spesialis jantung jika ada keluhan terkait hasil EKG abnormal,ECG: Sinus bradycardia HR [XX] bpm normoaxis,Consult a cardiologist if there are complaints regarding abnormal ECG results
EKG,EKG,EKG RAD,50-99,"EKG: Sinus rhythm HR [XX] bpm, RAD",Konsultasi dengan dokter spesialis jantung jika ada keluhan terkait hasil EKG abnormal,"ECG: Sinus rhythm HR [XX] bpm, RAD",Consult a cardiologist if there are complaints regarding abnormal ECG results
EKG,EKG,EKG LAD,50-99,"EKG: Sinus rhythm HR [XX] bpm, LAD",Konsultasi dengan dokter spesialis jantung jika ada keluhan terkait hasil EKG abnormal,"ECG: Sinus rhythm HR [XX] bpm, LAD",Consult a cardiologist if there are complaints regarding abnormal ECG results
TREADMILL,Treadmill,TMT,Iskemik,Treadmill test: Respon ischemic positive,Konsultasi dengan dokter spesialis jantung untuk pemeriksaan dan tatalaksana lebih lanjut terkait hasil Treadmill Test abnormal,Treadmill test: Positive ischemic response,Consult a cardiologist for further evaluation and management of abnormal Treadmill Test results
USG,USG Abdomen,USG Abd,[text_input],USG Whole Abdomen: [text_input],Konsultasi dengan dokter spesialis penyakit dalam untuk pemeriksaan dan tata laksana lebih lanjut terkait hasil USG Abdomen abnormal,USG Whole Abdomen: [text_input],Consult an internist for further evaluation and management of abnormal abdominal ultrasound results
USG,USG Mammae,USG MM,[text_input],USG Mammae: [text_input],Konsultasi dengan dokter spesialis bedah onkologi untuk pemeriksaan dan tata laksana lebih lanjut terkait hasil USG Mammae abnormal,USG Mammae: [text_input],Consult a surgical oncologist for further evaluation and management of abnormal breast ultrasound results
SSBC,SSBC,SSBC,[text_input],SSBC: [text_input],Konsultasi dengan dokter spesialis obsgyn untuk pemeriksaan dan tata laksana lebih lanjut terkait hasil SSBC abnormal,SSBC: [text_input],Consult an Ob-Gyn specialist for further evaluation and management of abnormal Papsmear results
KONSUL,Konsul Gizi,Konsul Gizi,,,Konsultasi dengan dokter spesialis gizi klinik untuk tata laksana lebih lanjut terkait obesitas,,Consult a clinical nutrition specialist for further management of obesity
KONSUL,Konsul Dokter,Konsul sppd,[text_input],,Konsultasi dengan dokter spesialis penyakit dalam untuk pemeriksaan dan tata laksana lebih lanjut terkait [text_input],,Consult an internist for further evaluation and management of [text_input]
KONSUL,Konsul Dokter,Konsul spog,[text_input],,Konsultasi dengan dokter spesialis obsgyn untuk pemeriksaan dan tata laksana lebih lanjut terkait [text_input],,Consult an Ob-Gyn specialist for further evaluation and management of [text_input]
KONSUL,Konsul Dokter,Konsul sps,[text_input],,Konsultasi dengan dokter spesialis saraf untuk pemeriksaan dan tata laksana lebih lanjut terkait [text_input],,Consult a neurologist for further evaluation and management of [text_input]
KONSUL,Konsul Dokter,Konsul spb,[text_input],,Konsultasi dengan dokter spesialis bedah untuk pemeriksaan dan tata laksana lebih lanjut terkait [text_input],,Consult a surgeon for further evaluation and management of [text_input]
KONSUL,Konsul Dokter,Konsul spot,[text_input],,Konsultasi dengan dokter spesialis orthopedi untuk pemeriksaan dan tata laksana lebih lanjut terkait [text_input],,Consult an orthopedic specialist for further evaluation and management of [text_input]
ANAMNESIS,Keluhan,Keluhan,[text_input],Keluhan saat ini: [text_input],Konsultasi dengan dokter untuk pemeriksaan dan tata laksana lebih lanjut terkait keluhan saat ini,Current complaints: [text_input],Consult a doctor for further evaluation and management of current complaints
"""

# ==========================================
# 2. HELPER FUNCTIONS
# ==========================================

def load_db(csv_text):
    # Load sebagai string agar data kosong tidak otomatis jadi NaN (float)
    df = pd.read_csv(io.StringIO(csv_text), dtype=str)
    # Ganti NaN dengan string kosong
    return df.fillna("")